import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, type FirstBoardComparison, type FirstBoardConfig, type FirstBoardResearch, type FirstBoardRules, type FirstBoardSummary } from '@/lib/api'
import { QK } from '@/lib/queryKeys'
import { beijingDay, buttonClass, ErrorNotice, inputClass, LoadingRows, money, Notice, panelClass, patternLabels, pct, stamp } from './shared'

function SummaryTable({ rows }: { rows: { label: string; summary: FirstBoardSummary }[] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs" aria-label="日线观察统计"><thead><tr className="text-secondary">{['范围', '候选样本', '触板观察率', '收盘封板率', '次日开盘平均变化', '次日收盘平均变化', '次日收盘上涨占比'].map(label => <th key={label} className="px-3 py-2 font-normal first:pl-0">{label}</th>)}</tr></thead><tbody>{rows.map(({ label, summary: s }) => <tr key={label} className="border-t border-border"><th className="py-3 pr-3 font-medium">{label}</th><td className="px-3 py-3 tabular-nums">{s.candidates}</td><td className="px-3 py-3 tabular-nums">{pct(s.touch_rate)}<span className="mt-1 block text-secondary">{s.touched} / {s.touch_observed}</span></td><td className="px-3 py-3 tabular-nums">{pct(s.seal_rate)}<span className="mt-1 block text-secondary">{s.sealed} / {s.seal_observed}</span></td><td className="px-3 py-3 tabular-nums">{pct(s.next_open_mean)}<span className="mt-1 block text-secondary">{s.next_open_count} 个有效样本</span></td><td className="px-3 py-3 tabular-nums">{pct(s.next_close_mean)}<span className="mt-1 block text-secondary">{s.next_close_count} 个有效样本</span></td><td className="px-3 py-3 tabular-nums">{pct(s.next_positive_rate)}</td></tr>)}</tbody></table></div>
}

function Limitations({ items }: { items: string[] }) {
  return <details className="text-xs text-secondary"><summary className="cursor-pointer py-2">数据覆盖与解释边界</summary><ul className="ml-4 list-disc space-y-2 leading-relaxed">{items.map(item => <li key={item}>{item}</li>)}</ul></details>
}

export function ResearchPanel({ config, versions, onOpenStock, onLoadRules }: {
  config: FirstBoardConfig; versions: FirstBoardConfig[]; onOpenStock: (symbol: string, name: string) => void; onLoadRules: (rules: FirstBoardRules) => void
}) {
  const client = useQueryClient()
  const [start, setStart] = useState(() => beijingDay(-90))
  const [end, setEnd] = useState(() => beijingDay(-1))
  const [revision, setRevision] = useState('current')
  const [result, setResult] = useState<FirstBoardResearch | FirstBoardComparison | null>(null)
  const runs = useQuery({ queryKey: QK.firstBoardResearchRuns, queryFn: api.firstBoardResearchRuns })
  const version = revision === 'current' ? config : versions.find(item => String(item.revision) === revision)
  const request = { start, end, rules: version?.rules }
  const research = useMutation({ mutationFn: () => api.firstBoardResearch(request), onSuccess: value => { setResult(value); void client.invalidateQueries({ queryKey: QK.firstBoardResearchRuns }) } })
  const compare = useMutation({ mutationFn: () => api.firstBoardCompare(request), onSuccess: value => { setResult(value); void client.invalidateQueries({ queryKey: QK.firstBoardResearchRuns }) } })
  const busy = research.isPending || compare.isPending
  const validDates = !!start && !!end && start <= end && end < beijingDay() && (Date.parse(end) - Date.parse(start)) / 86400000 < 366
  const study = result && 'summary' in result ? result : null
  const comparison = result && 'variants' in result ? result : null
  function clearResult() { setResult(null); research.reset(); compare.reset() }

  return <div className="space-y-4">
    <Notice>这里验证形态的日线表现，展示触板、收盘封板和次日价格变化。没有假设信号时刻买入，也未计入交易成本，不能作为交易胜率。模拟成交表现请结合模拟盘记录。</Notice>
    <section className={`${panelClass} space-y-4`}><h2 className="text-sm font-semibold">历史观察与规则比较</h2><div className="flex flex-wrap items-end gap-3">
      <label className="min-w-40 flex-1 space-y-1.5 text-xs text-secondary"><span>开始日期</span><input type="date" className={inputClass} max={end} value={start} disabled={busy} onChange={e => { setStart(e.target.value); clearResult() }} /></label>
      <label className="min-w-40 flex-1 space-y-1.5 text-xs text-secondary"><span>结束日期</span><input type="date" className={inputClass} min={start} max={beijingDay(-1)} value={end} disabled={busy} onChange={e => { setEnd(e.target.value); clearResult() }} /></label>
      <label className="min-w-40 flex-1 space-y-1.5 text-xs text-secondary"><span>研究规则</span><select className={inputClass} value={revision} disabled={busy} onChange={e => { setRevision(e.target.value); clearResult() }}><option value="current">当前版本 {config.revision}</option>{versions.filter(item => item.revision !== config.revision).map(item => <option key={item.revision} value={item.revision}>历史版本 {item.revision}</option>)}</select></label>
      <button className={buttonClass} disabled={busy || !validDates || !version} onClick={() => { setResult(null); compare.reset(); research.mutate() }}>{research.isPending ? '正在研究…' : '运行日线研究'}</button>
      <button className={buttonClass} disabled={busy || !validDates || !version} onClick={() => { setResult(null); research.reset(); compare.mutate() }}>{compare.isPending ? '正在比较…' : '比较实验参数'}</button>
    </div><p className="text-xs leading-relaxed text-secondary">每次最多 366 个自然日。参数比较按时间划分训练区间与留出验证区间，仅依据训练区间选择候选规则，不自动应用。</p>{!validDates && <Notice error>请选择早于北京时间今天的有效日期区间，跨度最多 366 天。</Notice>}</section>
    <ErrorNotice error={research.error ?? compare.error} />
    {busy && <LoadingRows />}
    {study && <section className={`${panelClass} space-y-4`}><h2 className="text-sm font-semibold">日线观察结果</h2><p className="text-xs leading-relaxed text-secondary">{study.methodology}</p><div className="flex flex-wrap gap-x-6 gap-y-2 text-xs text-secondary"><span>研究区间：{String(study.data_window.requested_start ?? study.coverage.sessions[0] ?? '—')} 至 {String(study.data_window.requested_end ?? study.coverage.sessions.at(-1) ?? '—')}</span><span>覆盖交易日：{study.coverage.session_count}</span><span>股票与日期去重：{study.summary.unique_stock_days}</span><span>日线缺口：{study.coverage.missing_days.length}</span><span>观察缺失：{study.coverage.missing_observations}</span><span>次日结果缺失：{study.coverage.missing_outcomes}</span></div>{!study.coverage.history_sufficient && <Notice>前置历史数据不足。缺少足够连续历史的股票不会进入候选。</Notice>}{study.summary.candidates === 0 ? <Notice>所选区间没有可验证的候选样本。请检查本地日线覆盖、历史长度或调整研究规则。</Notice> : <SummaryTable rows={[{ label: '全部形态', summary: study.summary }, ...Object.entries(study.by_pattern).map(([pattern, summary]) => ({ label: patternLabels[pattern as keyof typeof patternLabels] ?? pattern, summary }))]} />}
      {!!study.samples.length && <details><summary className="cursor-pointer text-sm">样本明细（展示 {study.samples.length} / {study.total_samples}）</summary><div className="mt-3 max-h-[32rem] overflow-auto"><table className="w-full min-w-[760px] text-left text-xs" aria-label="研究样本明细"><thead><tr className="text-secondary">{['日期', '股票', '形态', '收盘价', '触板 / 收盘封板', '次日开盘', '次日收盘', '数据说明'].map(label => <th key={label} className="px-2 py-2 font-normal">{label}</th>)}</tr></thead><tbody>{study.samples.map((sample, index) => <tr key={`${sample.date}-${sample.symbol}-${sample.pattern}-${index}`} className="border-t border-border"><td className="px-2 py-2">{sample.date}</td><td className="px-2 py-2"><button className="text-left hover:underline focus-visible:outline focus-visible:outline-accent" onClick={() => onOpenStock(sample.symbol, sample.name)}>{sample.name}<span className="block text-secondary">{sample.symbol}</span></button></td><td className="px-2 py-2">{sample.pattern_label}</td><td className="px-2 py-2 tabular-nums">{money(sample.observed_close)}</td><td className="px-2 py-2">{sample.touched == null ? '未知' : sample.touched ? '是' : '否'} / {sample.sealed == null ? '未知' : sample.sealed ? '是' : '否'}</td><td className="px-2 py-2 tabular-nums">{pct(sample.next_open_return)}</td><td className="px-2 py-2 tabular-nums">{pct(sample.next_close_return)}</td><td className="max-w-48 px-2 py-2 leading-relaxed text-secondary">{sample.gap_reasons.join('；') || '—'}</td></tr>)}</tbody></table></div>{study.samples_truncated && <p className="mt-2 text-xs text-secondary">明细已截取，汇总指标仍基于全部候选样本。</p>}</details>}
      <Limitations items={study.limitations} />
    </section>}
    {comparison && <section className={`${panelClass} space-y-4`}><h2 className="text-sm font-semibold">训练与留出验证</h2><div className="flex flex-wrap gap-x-8 gap-y-2 text-xs text-secondary"><span>训练：{comparison.train.sessions[0] ?? '—'} 至 {comparison.train.sessions.at(-1) ?? '—'}（{comparison.train.session_count} 日）</span><span>验证：{comparison.validation.sessions[0] ?? '—'} 至 {comparison.validation.sessions.at(-1) ?? '—'}（{comparison.validation.session_count} 日）</span></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs" aria-label="规则比较"><thead><tr className="text-secondary">{['实验规则', '训练封板率 / 有效样本', '验证封板率 / 有效样本', '选择情况', '操作'].map(label => <th key={label} className="px-3 py-2 font-normal first:pl-0">{label}</th>)}</tr></thead><tbody>{comparison.variants.map(variant => <tr key={variant.id} className="border-t border-border"><th className="py-3 pr-3 font-medium">{variant.label}</th><td className="px-3 py-3 tabular-nums">{pct(variant.train.seal_rate)} / {variant.train.seal_observed}</td><td className="px-3 py-3 tabular-nums">{pct(variant.validation.seal_rate)} / {variant.validation.seal_observed}</td><td className="px-3 py-3">{variant.id === comparison.training_selected_id ? '训练选中' : '未选中'}</td><td className="px-3 py-3"><button className={buttonClass} onClick={() => onLoadRules(variant.rules)}>载入草稿审阅</button></td></tr>)}</tbody></table></div><Notice>{comparison.recommendation_reason}。规则尚未自动应用。</Notice><p className="text-xs text-secondary">最低有效样本：训练 {comparison.minimum_samples.train}，验证 {comparison.minimum_samples.validation}。每次重新试验都会使用验证区间，反复调参仍可能过拟合，应保留后续新数据观察。</p><Limitations items={comparison.limitations} /></section>}
    <section className={panelClass}><h2 className="mb-3 text-sm font-semibold">已保存的研究记录</h2><ErrorNotice error={runs.error} retry={() => void runs.refetch()} />{runs.isLoading ? <LoadingRows /> : runs.data?.runs.length ? <ul className="divide-y divide-border">{runs.data.runs.map(run => <li key={run.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-xs"><span>{'variants' in run.result ? '规则比较' : '日线观察'} · {stamp(run.created_at)}</span><button className={buttonClass} disabled={busy} onClick={() => { setResult(run.result); research.reset(); compare.reset() }}>查看结果</button></li>)}</ul> : <p className="text-sm text-secondary">研究结果自动保存，这里显示最近 10 次，便于复核。</p>}</section>
  </div>
}
