import type { MarketGameAdaptation, MarketGameExecutionEvaluation } from '@/lib/api'
import { cn } from '@/lib/cn'

const panel = 'min-w-0 rounded-card border border-border bg-surface/80 p-4'
const warning = 'text-amber-700 dark:text-warning'
const modes: Record<string, string> = { panic_repair: '恐慌修复', trend_pullback: '趋势回撤', crowded_exit: '拥挤退潮' }
const regimes: Record<string, string> = { expanding: '扩散增强', rotation: '存量轮动', concentrated: '缩量集中', contracting: '风险收缩', unconfirmed: '环境待确认' }
const states = { pending: '等待观察', unavailable: '无法核验', no_entry: '未入场', open: '退出未完成', exited: '模拟已退出', not_executable: 'T+1 不具备卖出资格' }
const evaluationStates = { pending: '等待观察', partial: '部分可核验', complete: '评估完成', unavailable: '暂无可核验结果' }
const adaptationStates = { insufficient: '样本不足', observing: '继续观察', weakening: '衰减候选' }
const percent = (value: number | null) => value == null || !Number.isFinite(value) ? '—' : `${(value * 100).toFixed(2)}%`
const price = (value: number | null) => value == null || !Number.isFinite(value) ? '—' : value.toFixed(2)
const signed = (value: number | null) => value == null || value === 0 ? 'text-secondary' : value > 0 ? 'text-red-700 dark:text-bull' : 'text-emerald-700 dark:text-bear'
function time(value: string | null) {
  if (!value) return '—'
  const date = new Date(/(?:Z|[+-]\d{2}:?\d{2})$/.test(value) ? value : `${value}+08:00`)
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('zh-CN', { timeZone: 'Asia/Shanghai', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(date)
}
function Limits({ items }: { items: string[] }) {
  return items.length ? <details className="mt-3 border-t border-border pt-1 text-xs"><summary className="min-h-9 cursor-pointer py-2 font-medium">评估依据与限制 · {items.length} 项</summary><ul className="max-w-prose space-y-1 pb-2 leading-relaxed text-secondary">{items.map((item, index) => <li key={`${index}-${item}`}>{item}</li>)}</ul></details> : null
}

export function ExecutionPanel({ execution, adaptation }: { execution: MarketGameExecutionEvaluation | null; adaptation: MarketGameAdaptation | null }) {
  return <>
    <section aria-label="交易执行评估" className={panel}>
      <div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-sm font-semibold">交易执行评估</h2>{execution && <span className={cn('text-xs', execution.status === 'complete' ? 'text-secondary' : warning)}>{evaluationStates[execution.status]}</span>}</div>
      <p className="mt-1 max-w-prose text-xs leading-relaxed text-secondary">按冻结条件、可得分钟数据、T+1 与成本假设进行模拟。未完成退出的观察不显示净收益，也不作为成熟成交样本。</p>
      {!execution ? <p className="mt-4 text-sm text-secondary">尚无执行评估。更新模型验证后，将明确区分未触发、无法核验与模拟成交结果。</p> : <>
        <p className="mt-3 text-xs text-secondary">评估时点 {time(execution.evaluated_at)}（北京时间） · {execution.rows.length} 只原计划候选</p>
        {execution.rows.length ? <div className="mt-3 divide-y divide-border">{execution.rows.map(row => <article key={row.symbol} className="py-4 first:pt-0 last:pb-0">
          <div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-sm font-semibold">{row.name}<span className="ml-2 font-mono text-xs font-normal text-secondary">{row.symbol}</span></h3><span className="text-xs text-secondary">{modes[row.mode] ?? '未归类策略'} · {regimes[row.regime] ?? row.regime} · {row.sector}</span></div>
          <p className="mt-2 text-xs leading-relaxed text-secondary">{row.reason}</p>
          <dl className="mt-3 flex flex-wrap gap-x-6 gap-y-2 text-xs"><div><dt className="inline text-secondary">条件时点 </dt><dd className="inline font-mono">{time(row.signal_time)}</dd></div><div><dt className="inline text-secondary">模拟入场 </dt><dd className="inline font-mono">{time(row.entry_time)}</dd></div><div><dt className="inline text-secondary">入场价 </dt><dd className="inline font-mono">{price(row.entry_price)}</dd></div><div><dt className="inline text-secondary">模拟股数 </dt><dd className="inline font-mono">{row.quantity.toLocaleString('zh-CN')}</dd></div></dl>
          <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><caption className="sr-only">{row.name}各观察期限的模拟退出与成熟状态</caption><thead className="border-b border-border text-secondary"><tr>{['观察期限', '目标交易日', '执行状态', '退出时点 / 价格', '模拟净收益', '结果可得时间', '说明'].map(label => <th key={label} scope="col" className="py-2 pr-4 font-medium">{label}</th>)}</tr></thead><tbody>{row.labels.map(label => {
            const matureReturn = label.mature && label.state === 'exited' ? label.net_return : null
            return <tr key={label.horizon} className="border-b border-border/60"><td className="py-3 pr-4">第 {label.horizon} 个交易日</td><td className="pr-4 font-mono">{label.trade_date ?? '—'}</td><td className={cn('pr-4', label.state === 'open' || label.state === 'pending' ? warning : 'text-secondary')}>{states[label.state]}</td><td className="pr-4 font-mono">{time(label.exit_time)}<span className="block">{price(label.exit_price)}</span></td><td className={cn('pr-4 font-mono', signed(matureReturn))}>{percent(matureReturn)}</td><td className="pr-4 font-mono">{time(label.outcome_available_at)}</td><td className="max-w-xs py-3 leading-relaxed text-secondary">{label.reason}</td></tr>
          })}</tbody></table></div>
        </article>)}</div> : <p className="mt-4 text-sm text-secondary">此计划没有可评估的候选。</p>}
        <details className="mt-3 border-t border-border pt-1 text-xs"><summary className="min-h-9 cursor-pointer py-2 font-medium">模拟成本与成交假设</summary><dl className="grid gap-x-6 gap-y-2 pb-2 sm:grid-cols-2"><div><dt className="inline text-secondary">假设账户规模 </dt><dd className="inline font-mono">{execution.costs.account_equity.toLocaleString('zh-CN')} 元</dd></div><div><dt className="inline text-secondary">佣金 </dt><dd className="inline font-mono">{percent(execution.costs.commission_rate)}，最低 {execution.costs.minimum_commission} 元</dd></div><div><dt className="inline text-secondary">卖出税率 </dt><dd className="inline font-mono">{percent(execution.costs.sell_tax_rate)}</dd></div><div><dt className="inline text-secondary">过户费率 </dt><dd className="inline font-mono">{(execution.costs.transfer_rate * 100).toFixed(3)}%</dd></div><div><dt className="inline text-secondary">滑点假设 </dt><dd className="inline font-mono">{percent(execution.costs.slippage)}</dd></div><div><dt className="inline text-secondary">成交量参与上限 </dt><dd className="inline font-mono">{percent(execution.costs.max_volume_participation)}</dd></div></dl><p className="pb-2 leading-relaxed text-secondary">以上为研究假设，实际费用与成交情况以账户和交易记录为准。</p></details>
        <Limits items={[...execution.evidence_summary, ...execution.limitations]} />
      </>}
    </section>
    <section aria-label="策略适应性" className={panel}>
      <div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-sm font-semibold">策略适应性</h2><span className="text-xs text-secondary">自动调仓未启用</span></div>
      <p className="mt-1 max-w-prose text-xs leading-relaxed text-secondary">按策略、市场环境与观察期限分组，只统计已成熟的模拟净收益。当前是描述性研究，尚未完成样本外验证。</p>
      {!adaptation || !adaptation.groups.length ? <p className="mt-4 text-sm text-secondary">尚无可分组的执行记录。候选后续涨跌不会自动作为策略成交收益。</p> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><caption className="sr-only">不同市场环境中的策略成熟样本与适应性观察</caption><thead className="border-b border-border text-secondary"><tr>{['策略 / 环境', '观察期限', '成熟样本 / 信号日期', '排除样本', '样本平均净收益', '适应性判断'].map(label => <th key={label} scope="col" className="py-2 pr-4 font-medium">{label}</th>)}</tr></thead><tbody>{adaptation.groups.map(group => <tr key={group.id} className="border-b border-border/60"><td className="py-3 pr-4">{modes[group.mode] ?? '未归类策略'}<span className="mt-1 block text-secondary">{regimes[group.regime] ?? group.regime}</span><span className="mt-1 block text-secondary">规则 {group.rule_version} · 分组 {group.id.slice(0, 6)}</span></td><td className="pr-4">{group.horizon} 个交易日</td><td className="pr-4 font-mono">{group.sample_size} / {group.independent_dates}</td><td className="pr-4 font-mono">{group.excluded_count}</td><td className={cn('pr-4 font-mono', signed(group.mean_net_return))}>{percent(group.mean_net_return)}</td><td className="max-w-xs py-3"><span className={cn('font-medium', group.state === 'weakening' ? warning : 'text-secondary')}>{adaptationStates[group.state]}</span><p className="mt-1 leading-relaxed text-secondary">{group.reason}</p></td></tr>)}</tbody></table></div>}
      <p className="mt-3 max-w-prose text-xs leading-relaxed text-secondary">同一日期或题材的结果可能相关。样本数与日期数用于说明覆盖，不表示同等数量的独立试验；样本均值不是未来收益预测。</p>
      {!!adaptation?.groups.length && <details className="mt-3 border-t border-border pt-1 text-xs"><summary className="min-h-9 cursor-pointer py-2 font-medium">按时间滚动对照</summary><p className="mb-3 max-w-prose leading-relaxed text-secondary">对照时只使用入场前已知的成熟样本，剔除重叠窗口并隔离最近日期。这里比较已退出样本中的固定规则与历史表现过滤，不能代表完整策略的样本外收益。</p><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><caption className="sr-only">固定规则与历史表现过滤的滚动研究对照</caption><thead className="border-b border-border text-secondary"><tr>{['策略 / 分组', '训练门槛', '对照 / 保留 / 暂停日期', '固定规则均值', '过滤后均值', '均值差', '对照说明'].map(label => <th key={label} scope="col" className="py-2 pr-4 font-medium">{label}</th>)}</tr></thead><tbody>{adaptation.groups.map(group => <tr key={group.id} className="border-b border-border/60"><td className="py-3 pr-4">{modes[group.mode] ?? '未归类策略'} · {group.horizon} 日<span className="mt-1 block text-secondary">{group.id.slice(0, 6)}</span></td><td className="pr-4">{group.walk_forward.training_min_dates} 个日期</td><td className="pr-4 font-mono">{group.walk_forward.test_dates} / {group.walk_forward.accepted_dates} / {group.walk_forward.withheld_dates}</td><td className={cn('pr-4 font-mono', signed(group.walk_forward.fixed_mean_net_return))}>{percent(group.walk_forward.fixed_mean_net_return)}</td><td className={cn('pr-4 font-mono', signed(group.walk_forward.filtered_mean_net_return))}>{percent(group.walk_forward.filtered_mean_net_return)}</td><td className={cn('pr-4 font-mono', signed(group.walk_forward.difference))}>{group.walk_forward.difference == null ? '—' : `${(group.walk_forward.difference * 100).toFixed(2)} 个百分点`}</td><td className="max-w-xs py-3 leading-relaxed text-secondary"><span className="font-medium">{group.walk_forward.state === 'insufficient' ? '样本不足' : '仅供研究对照'}</span><p className="mt-1">{group.walk_forward.reason}</p></td></tr>)}</tbody></table></div></details>}
      {adaptation && <Limits items={adaptation.limitations} />}
    </section>
  </>
}
